name: Benchmarks

on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

jobs:
  bench:
    name: Benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Print enabled target features
        run: rustc --print=cfg

      - name: Benchmark
        uses: actions-rs/cargo@v1
        with:
          command: bench

  bench-native:
    name: Benchmark (cpu=native)
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -C target-cpu=native

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true

      - name: Print enabled target features
        run: rustc --print=cfg -C target-cpu=native

      - name: Benchmark
        uses: actions-rs/cargo@v1
        with:
          command: bench
