on:
  push:
    branches: master
  pull_request:

name: Code formatting check

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.75.0
          components: rustfmt

      - run: cargo +stable fmt --all -- --check
